version: '3.7'

services:

# Java 8 - OpenJdk

  # Alpine 3.8
  openjdk-8u201:
    image: jtim/docker-docker-compose-jdk:18.05.0-ce-git-compose-1.21.2-openjdk-8u191
    build:
      context: java8/openjdk/8u201

# Java 11 - Adopt Openjdk

  docker-docker-compose-jdk-adoptopenjdk-11:
    image: jtim/docker-docker-compose-jdk:18.09.3-ce-git-compose-1.23.2-adoptopenjdk-11.0.2.9
    build:
      context: java11/adoptopenjdk/11.0.2.9